spring.application.name=wildcards
# ===============================
# DATASOURCE
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/wildcards
spring.datasource.username=wildcards
spring.datasource.password=wildcards
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=MzJieXRlc2xvbmdzZWNyZXRrZXlmb3Jqd3RzaWduaW5n
jwt.expiration=3600000


# Clave publicable (segura para usar en el frontend)
stripe.key.public=pk_test_51TA4pECCdDp5MHKnMNkptLX62A29ThhvbtpzUWkdcz2V8fdVBWt6D3Mcj0gXvPkJAUJzU6vrdQlsEwTQ5tdXNUSW00mGJK4KzK

# Clave secreta (MANTENER EN SECRETO, NUNCA EXPONER EN EL FRONTEND)
stripe.key.secret=sk_test_51TA4pECCdDp5MHKn3aWkh166Dpk5R9H4kpeDp6zp08cqsvPnA8v0eeXZJPweEXULL2qHRiC32FYSnIiQOtScZxWZ00ysoBfj0h

# Secreto del Webhook (para verificar las peticiones de Stripe)
stripe.webhook.secret=whsec_2ed059261a4aafe8e05c645aea80efed06183eedcd676c806cd82ce63f44745a
